---
# Whether to give the bot a bot tag (true) or not (false). Recommended to mark it but the option is here if you already 
# marked it manually and it starts throwing user_already_exists errors
markAsBot: false

# How often to update the remind times in minutes
timeCheckInterval: 1

# Set to true if you want to see log messages. False if not
# (Note I cant control log messages sent by the bot library so those will still show. Just ones thrown by the bot wont)
showLogs: true


# ------------------------------------------------------------------------------


responseMessage: |
  Gotcha! I'll remind you at ${TIME}.

invalidMessage: |
  Sorry, I didn't understand that reminder. Please try again.

  Make sure you're including the interval until you want to be reminded.

  ```
  Example: "Remind me about my dentist appointment in 2 hours"
  Example: "Message me in 5 minutes"
  ```

  For any issues contact my developer: [Ategon](/u/ategon@programming.dev)

overflowMessage: |
  Sorry, I can't remind you that far in the future. Please try again.

  The maximum allowed time is 10 years.

  For any issues contact my developer: [Ategon](/u/ategon@programming.dev)

finalMessage: |
  Hey, here is your reminder!